#!/usr/bin/env python3
"""Sweep the R5D checked-in transcript excerpt out of a real `llama-eval-callback` capture.

`docs/specs/r5d-moe-layer-forward.md` section 5.2: the excerpt exists so a change to the oracle's
*parsing* is caught hosted, against real instrument formatting — including the two **integer**
blocks, which no other checked-in excerpt carries — without a 4.2 GB model. It is regenerated by
`scripts/run-moe-layer-forward` rather than edited, which is what keeps it from going stale, and it
is swept for paths, usernames, and non-ASCII bytes before it is written.

    python3 scripts/sweep-moe-layer-forward-excerpt.py TRANSCRIPT OUTPUT
"""

import re
import sys

# The attention output projection has **no stable name**: it prints as a positional `node_NN` that
# moves when anything upstream changes, so `src/moe_layer_forward.align` matches it by its source
# weight and this sweep does the same.
ATTN_OUTPUT = "@attn_output"
ATTN_OUTPUT_RE = re.compile(r"blk\.\d+\.attn_output\.weight$")

# The twenty-eight records this oracle **scans**: the twenty-six of section 3.6 plus `kq-0` and
# `kq_soft_max-0`, which are matched and then excluded from element comparison by contract. The
# four `norm-0` records and the fourteen reduction records are deliberately absent — section 2.2
# facts 4 and 5 record that their names are ambiguous and unstable, so the arm never seeks them.
WANT = [
    ("embd", "GET_ROWS"), ("attn_norm-0", "MUL"),
    ("Qcur-0", "MUL_MAT"), ("Qcur_normed-0", "MUL"), ("Qcur-0", "ROPE"),
    ("Kcur-0", "MUL_MAT"), ("Kcur_normed-0", "MUL"), ("Kcur-0", "ROPE"),
    ("Vcur-0", "MUL_MAT"),
    ("kq-0", "MUL_MAT"), ("kq_soft_max-0", "SOFT_MAX"), ("kqv-0", "MUL_MAT"),
    ("kqv_out-0", "CONT"), (ATTN_OUTPUT, "MUL_MAT"), ("ffn_inp-0", "ADD"),
    ("ffn_norm-0", "MUL"),
    ("ffn_moe_logits-0", "MUL_MAT"), ("ffn_moe_probs-0", "SOFT_MAX"),
    ("ffn_moe_argsort-0", "ARGSORT"), ("ffn_moe_topk-0", "VIEW"),
    ("ffn_moe_weights-0", "GET_ROWS"),
    ("ffn_moe_gate-0", "MUL_MAT_ID"), ("ffn_moe_up-0", "MUL_MAT_ID"),
    ("ffn_moe_swiglu-0", "SWIGLU"), ("ffn_moe_down-0", "MUL_MAT_ID"),
    ("ffn_moe_weighted-0", "MUL"), ("ffn_moe_out-0", "ADD"), ("l_out-0", "ADD"),
]

HEADER = """# R5D-MOE-LAYER-FORWARD checked-in transcript excerpt.
#
# docs/specs/r5d-moe-layer-forward.md section 5.2. The twenty-eight blk.0 records the routed
# oracle scans, verbatim, in transcript order: the twenty-six compared nodes of section 3.6 plus
# kq-0 and kq_soft_max-0, which are present, matched, and excluded from element comparison by
# contract because llama.cpp's n_kv is a padded KV-cache width and R5D has no cache.
#
# The four norm-0 records and the fourteen ffn_moe_weighted-0 (view) / node_NN reduction records
# are deliberately absent: section 2.2 facts 4 and 5 record that four different tensors of one
# OLMoE layer print under the name norm-0 and that the reduction chain's names are positional, so
# the arm never seeks either class and each is published as an oracle exclusion instead.
#
# It is swept from scripts/run-moe-layer-forward, which regenerates it, and it exists so that a
# change to the oracle's *parsing* is caught hosted, against real formatting, without a 4.2 GB
# model. It is the only checked-in excerpt carrying **integer** blocks: ffn_moe_argsort-0 and
# ffn_moe_topk-0 print i32 expert ids through %12.4f, which r2a-expert-trace.md section 2.2
# finding 5's rule parses as integers and never as rounded floats.
#
# Instrument: llama-eval-callback, llama.cpp 0.2.0 (build 10566, commit bb4caa754).
# Model:      OLMoE-1B-7B-0125-Instruct-Q4_K_M.gguf
# Command:    llama-eval-callback -m MODEL.gguf -p 'def add(a, b' -n 1 -t 4 -ngl 0 \\
#                 -fa off -ctk f32 -ctv f32 -nr -c 512
# Tokens:     1545 823 9 66 13 270
#
# The prompt is 'def add(a, b' and not R5A's 'def add(a, b):' because OLMoE's tokenizer produces
# seven ids for the latter and MAX_PREFILL_TOKENS is 6: an axis of extent above six prints only
# six of its positions, and an oracle that compares fewer elements as the input grows is worse
# than one that refuses.
#
# The four flags are contractual, not an invocation detail: build 10566 defaults to -fa auto,
# an f16 KV cache, and repacked quantized weights, and none of those three is the graph R5D
# computes. Trailing spaces on the '..., ' truncation markers are the instrument's own and are
# significant, which is why .gitattributes exempts this file from whitespace normalisation.
"""

FORBIDDEN = ("/Users", "/home/", "/private", "/opt/", "\\Users", "C:\\")

HEADER_RE = re.compile(r"^common_debug_cb_eval:\s+(\S.*?) = \((\w+)\)\s+(\w+)\(([^{]*)\{")


def key_of(match):
    """`(identity, op)`, where the attention output projection's identity is its source weight."""
    name, op, source = match.group(1), match.group(3), match.group(4).strip()
    if op == "MUL_MAT" and ATTN_OUTPUT_RE.search(source):
        return (ATTN_OUTPUT, op)
    return (name, op)


def sweep(source):
    lines = source.split("\n")
    taken = set()
    blocks = []
    at = 0
    while at < len(lines):
        match = HEADER_RE.match(lines[at])
        if not match:
            at += 1
            continue
        key = key_of(match)
        end = at + 1
        while end < len(lines) and not lines[end].startswith("    sum = "):
            end += 1
        if key in WANT and key not in taken:
            taken.add(key)
            blocks.append((WANT.index(key), lines[at:end + 1]))
        at = end + 1
    missing = [key for key in WANT if key not in taken]
    if missing:
        raise SystemExit("sweep-moe-layer-forward-excerpt: records absent: %r" % (missing,))
    blocks.sort(key=lambda row: row[0])
    body = []
    for _, block in blocks:
        body.extend(block)
    out = HEADER + "\n" + "\n".join(body) + "\n"
    for byte in out:
        if ord(byte) > 127:
            raise SystemExit("sweep-moe-layer-forward-excerpt: a non-ASCII byte survived the sweep")
    for needle in FORBIDDEN:
        if needle in out:
            raise SystemExit("sweep-moe-layer-forward-excerpt: %r survived the sweep" % needle)
    return out


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: sweep-moe-layer-forward-excerpt.py TRANSCRIPT OUTPUT\n")
        return 2
    with open(argv[1], "r", encoding="utf-8", errors="strict") as handle:
        source = handle.read()
    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write(sweep(source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
