#!/usr/bin/env python3
"""Sweep the R5A checked-in transcript excerpt out of a real `llama-eval-callback` capture.

`docs/specs/r5a-dense-layer-forward.md` section 5.1: the excerpt exists so a change to the oracle's
*parsing* is caught hosted, against real instrument formatting, without a 4.7 GB model. It is
regenerated by `scripts/run-layer-forward` rather than edited, which is what keeps it from going
stale, and it is swept for paths, usernames, and non-ASCII bytes before it is written.

    python3 scripts/sweep-layer-forward-excerpt.py TRANSCRIPT OUTPUT
"""

import re
import sys

# The twenty records, in transcript order: the eighteen oracle nodes of section 3.6 plus `kq-0` and
# `kq_soft_max-0`, which are matched and then excluded from element comparison by contract.
WANT = [
    ("embd", "GET_ROWS"), ("norm-0", "RMS_NORM"), ("attn_norm-0", "MUL"),
    ("Qcur-0", "ADD"), ("Vcur-0", "ADD"), ("Kcur-0", "ADD"),
    ("Qcur-0", "ROPE"), ("Kcur-0", "ROPE"),
    ("kq-0", "MUL_MAT"), ("kq_soft_max-0", "SOFT_MAX"), ("kqv-0", "MUL_MAT"),
    ("kqv_out-0", "CONT"), ("node_31", "MUL_MAT"), ("ffn_inp-0", "ADD"),
    ("ffn_norm-0", "MUL"), ("ffn_gate-0", "MUL_MAT"), ("ffn_up-0", "MUL_MAT"),
    ("ffn_swiglu-0", "SWIGLU"), ("ffn_out-0", "MUL_MAT"), ("l_out-0", "ADD"),
]

HEADER = """# R5A-DENSE-LAYER-FORWARD checked-in transcript excerpt.
#
# docs/specs/r5a-dense-layer-forward.md section 5.1. The twenty blk.0 records of section 2.2's
# transcript, verbatim, in transcript order: the eighteen oracle nodes plus kq-0 and
# kq_soft_max-0, which are present, matched, and excluded from element comparison by contract
# because llama.cpp's n_kv is a padded KV-cache width and R5A has no cache.
#
# It is swept from scripts/run-layer-forward, which regenerates it, and it exists so that a
# change to the oracle's *parsing* is caught hosted, against real formatting, without a 4.7 GB
# model. Its numbers are the qualification's; scripts/run-layer-forward-smoke compares only its
# grammar and its node identity.
#
# Instrument: llama-eval-callback, llama.cpp 0.2.0 (build 10566, commit bb4caa754).
# Model:      qwen2.5-coder-7b-instruct-q4_k_m.gguf
# Command:    llama-eval-callback -m MODEL.gguf -p 'def add(a, b):' -n 1 -t 4 -ngl 0 \\
#                 -fa off -ctk f32 -ctv f32 -nr -c 512
# Tokens:     750 912 2877 11 293 1648
#
# The four flags are contractual, not an invocation detail: build 10566 defaults to -fa auto,
# an f16 KV cache, and repacked quantized weights, and none of those three is the graph R5A
# computes. Trailing spaces on the '..., ' truncation markers are the instrument's own and are
# significant, which is why .gitattributes exempts this file from whitespace normalisation.
"""

FORBIDDEN = ("/Users", "/home/", "/private", "/opt/", "\\Users", "C:\\")

HEADER_RE = re.compile(r"^common_debug_cb_eval:\s+(\S.*?) = \((\w+)\)\s+(\w+)\(")


def sweep(source):
    lines = source.split("\n")
    taken = set()
    blocks = []
    at = 0
    while at < len(lines):
        match = HEADER_RE.match(lines[at])
        if not match:
            at += 1
            continue
        key = (match.group(1), match.group(3))
        end = at + 1
        while end < len(lines) and not lines[end].startswith("    sum = "):
            end += 1
        if key in WANT and key not in taken:
            taken.add(key)
            blocks.append((WANT.index(key), lines[at:end + 1]))
        at = end + 1
    missing = [key for key in WANT if key not in taken]
    if missing:
        raise SystemExit("sweep-layer-forward-excerpt: records absent: %r" % (missing,))
    blocks.sort(key=lambda row: row[0])
    body = []
    for _, block in blocks:
        body.extend(block)
    out = HEADER + "\n" + "\n".join(body) + "\n"
    for byte in out:
        if ord(byte) > 127:
            raise SystemExit("sweep-layer-forward-excerpt: a non-ASCII byte survived the sweep")
    for needle in FORBIDDEN:
        if needle in out:
            raise SystemExit("sweep-layer-forward-excerpt: %r survived the sweep" % needle)
    return out


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: sweep-layer-forward-excerpt.py TRANSCRIPT OUTPUT\n")
        return 2
    with open(argv[1], "r", encoding="utf-8", errors="strict") as handle:
        source = handle.read()
    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write(sweep(source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
