#!/usr/bin/env python3
"""Sweep the R5B checked-in transcript excerpt out of a real `llama-eval-callback` capture.

`docs/specs/r5b-model-prefill-forward.md` section 5.1: the whole transcript is 28,512 lines and
2,040,172 bytes, far too large to check in, and the excerpt exists so a change to the oracle's
*parsing* is caught hosted, against real instrument formatting **at whole-model scale**, without a
4.7 GB model. It is regenerated by `scripts/run-model-forward` rather than edited, which is what
keeps it from going stale, and it is swept for paths, usernames, and non-ASCII bytes before it is
written.

    python3 scripts/sweep-model-forward-excerpt.py TRANSCRIPT OUTPUT [N_LAYER]
"""

import re
import sys

# The attention output projection has **no stable name**: section 2.3 recorded it as `node_1084` at
# layer 27 under this flag set and as `node_31` in R5A's single-layer run, a positional name that
# moves with the layer as well as with the flags. `src/model_forward.align` matches it by its
# source weight in every one of the twenty-eight layers and this sweep must do the same.
ATTN_OUTPUT_RE = re.compile(r"blk\.(\d+)\.attn_output\.weight$")

HEADER_RE = re.compile(r"^common_debug_cb_eval:\s+(\S.*?) = \((\w+)\)\s+(\w+)\(([^{]*)\{")

HEADER = """# R5B-MODEL-PREFILL-FORWARD checked-in transcript excerpt.
#
# docs/specs/r5b-model-prefill-forward.md section 5.1. A whole-model slice of section 2.2's
# transcript, verbatim, in transcript order: `embd`, `kq-0`, whose declared `ne0` is the
# instrument's own reduction width and the one thing that record is good for, every `l_out-L`
# for L in 0..27, the layer-27 records that show where the prefill narrows, and the head's
# `result_norm` and `result_output`.
#
# It is swept from scripts/run-model-forward, which regenerates it, and it exists so that a change
# to the oracle's *parsing* is caught hosted, against real formatting at whole-model scale, without
# a 4.7 GB model. Its numbers are the qualification's; scripts/run-layer-forward-smoke compares
# only its grammar and its node identity.
#
# Instrument: llama-eval-callback, llama.cpp 0.2.0 (build 10566, commit bb4caa754).
# Model:      qwen2.5-coder-7b-instruct-q4_k_m.gguf
# Command:    llama-eval-callback -m MODEL.gguf -p 'def add(a, b):' -n 1 -t 4 -ngl 0 \\
#                 -fa off -ctk f32 -ctv f32 -nr -c 512
# Tokens:     750 912 2877 11 293 1648
#
# The six flags are contractual, not an invocation detail, and section 2.2 measured what dropping
# `-nr` costs: 0.30 of a logit, with the argmax unchanged. Trailing spaces on the '..., '
# truncation markers are the instrument's own and are significant, which is why .gitattributes
# exempts this file from whitespace normalisation.
"""

FORBIDDEN = ("/Users", "/home/", "/private", "/opt/", "\\Users", "C:\\")


def wanted(n_layer):
    """The thirty-five records, as `(identity, op)` keys in transcript order."""
    keys = [("embd", "GET_ROWS"), ("kq-0", "MUL_MAT")]
    keys.extend(("l_out-%d" % layer, "ADD") for layer in range(n_layer))
    last = n_layer - 1
    keys.extend([
        ("@attn_output-%d" % last, "MUL_MAT"),
        ("ffn_inp-%d" % last, "ADD"),
        ("ffn_norm-%d" % last, "MUL"),
        ("result_norm", "MUL"),
        ("result_output", "MUL_MAT"),
    ])
    return keys


def key_of(match):
    name, op, source = match.group(1), match.group(3), match.group(4).strip()
    if op == "MUL_MAT":
        weight = ATTN_OUTPUT_RE.search(source)
        if weight:
            return ("@attn_output-%s" % weight.group(1), op)
    return (name, op)


def sweep(source, n_layer):
    keys = wanted(n_layer)
    order = {key: index for index, key in enumerate(keys)}
    lines = source.split("\n")
    taken = set()
    blocks = []
    at = 0
    while at < len(lines):
        match = HEADER_RE.match(lines[at])
        if not match:
            at += 1
            continue
        key = key_of(match)
        end = at + 1
        while end < len(lines) and not lines[end].startswith("    sum = "):
            end += 1
        if key in order and key not in taken:
            taken.add(key)
            blocks.append((order[key], lines[at:end + 1]))
        at = end + 1
    missing = [key for key in keys if key not in taken]
    if missing:
        raise SystemExit("sweep-model-forward-excerpt: records absent: %r" % (missing,))
    blocks.sort(key=lambda row: row[0])
    body = []
    for _, block in blocks:
        body.extend(block)
    out = HEADER + "\n" + "\n".join(body) + "\n"
    for byte in out:
        if ord(byte) > 127:
            raise SystemExit("sweep-model-forward-excerpt: a non-ASCII byte survived the sweep")
    for needle in FORBIDDEN:
        if needle in out:
            raise SystemExit("sweep-model-forward-excerpt: %r survived the sweep" % needle)
    return out


def main(argv):
    if len(argv) not in (3, 4):
        sys.stderr.write("usage: sweep-model-forward-excerpt.py TRANSCRIPT OUTPUT [N_LAYER]\n")
        return 2
    n_layer = int(argv[3]) if len(argv) == 4 else 28
    with open(argv[1], "r", encoding="utf-8", errors="strict") as handle:
        source = handle.read()
    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write(sweep(source, n_layer))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
